(function(){'use strict';
const app=document.getElementById('eviaApp'),anchor=document.getElementById('eviaAnchor'),content=document.getElementById('content');
if(!app||!anchor||!content)return;
const style=document.createElement('style');
style.textContent='.evia-advice{position:absolute;z-index:19;left:50%;top:calc(50% + clamp(88px,24vw,108px));transform:translate(-50%,8px);width:min(88vw,430px);padding:11px 14px;border:1px solid rgba(218,181,40,.18);border-radius:15px;background:rgba(255,249,218,.96);box-shadow:0 7px 20px rgba(30,45,50,.06);text-align:center;opacity:0;pointer-events:none;transition:top 650ms cubic-bezier(.22,1,.36,1),transform 650ms cubic-bezier(.22,1,.36,1),opacity .25s ease}.evia-advice.visible{opacity:1;transform:translate(-50%,0)}.evia-advice b{display:block;margin-bottom:4px;font-size:.76rem;color:#806a16;opacity:0;transform:translateY(5px);transition:opacity .3s ease,transform .45s cubic-bezier(.22,1,.36,1)}.evia-advice.visible b{opacity:1;transform:translateY(0)}.evia-advice span{display:block;color:#625d42;font-size:.81rem;line-height:1.38;min-height:1.38em}.evia-advice .word{display:inline-block;white-space:nowrap;opacity:0;transform:translateY(8px);animation:eviaWord .42s cubic-bezier(.22,1,.36,1) forwards}.evia-app.is-open .evia-advice{top:calc(max(18px,env(safe-area-inset-top)) + 105px)}@keyframes eviaWord{to{opacity:1;transform:translateY(0)}}@media(max-width:420px){.evia-advice{width:calc(100vw - 28px);padding:10px 12px}.evia-advice span{font-size:.78rem}}';
document.head.appendChild(style);
const advice=document.createElement('div');advice.id='eviaAdvice';advice.className='evia-advice';advice.setAttribute('aria-live','polite');advice.innerHTML='<b>Evia’s advice</b><span></span>';anchor.insertAdjacentElement('afterend',advice);
const label=advice.querySelector('b'),text=advice.querySelector('span');
let lastKey='';
function photoAdvice(title){const t=String(title||'').toLowerCase();if(/ppe|personal protective/.test(t))return 'Show the PPE you are wearing for this task and make sure the work area is safe before you start.';if(/safe control|safety control|hazard|control/.test(t))return 'Show the safety controls you have put in place. Make the hazard and the control easy to see.';if(/tool selection|tools?/.test(t))return 'Show the tool you selected for the task and make sure it is suitable, safe and ready to use.';if(/measure|measurement|dimension|set out|mark/.test(t))return 'Show the measurement or mark clearly. Make sure the scale or numbers can be read in the photo.';if(/cut|cutting/.test(t))return 'Show the marked material, the cutting tool and the safe setup before you make the cut.';if(/mortar|mix/.test(t))return 'Show the materials, mixing method and finished consistency clearly. Include the gauge or ratio where possible.';if(/joint|pointing/.test(t))return 'Get close enough to show the joint profile and finished workmanship clearly.';if(/lintel|opening/.test(t))return 'Show the full opening, then make sure the bearing and surrounding masonry are clearly visible.';if(/insulation|dpc|tray|weep|fire stopping|firestop/.test(t))return 'Capture this detail before it is covered. Make sure the whole detail is visible and in focus.';if(/repair|defect/.test(t))return 'Show the defect clearly before the repair, then capture the finished repair.';if(/bond|solid wall/.test(t))return 'Stand square to the wall so the bond and workmanship are easy to see.';if(/pier|decorative|feature/.test(t))return 'Show the whole feature and then a closer view of the important bond or detail.';if(/protect|waste|complete|quality/.test(t))return 'Show the completed work, the quality checks and that the area has been left safe and tidy.';return 'Show the work or detail named above clearly. Make sure the photo is well lit, in focus and close enough to assess.';}
function set(labelText,value){const key=labelText+'|'+value;if(key===lastKey&&advice.classList.contains('visible'))return;lastKey=key;advice.classList.remove('visible');label.textContent=labelText;text.innerHTML='';String(value||'').split(/(\s+)/).forEach((part,i)=>{if(!part)return;if(/^\s+$/.test(part)){text.appendChild(document.createTextNode(' '));return}const s=document.createElement('span');s.className='word';s.textContent=part;s.style.animationDelay=(i*.055)+'s';text.appendChild(s)});requestAnimationFrame(()=>requestAnimationFrame(()=>advice.classList.add('visible')))}
function update(){if(!app.classList.contains('is-open')){set('Evia’s advice','Tap me and I’ll guide you through your evidence one step at a time.');return}const photo=content.querySelector('.capture-heading span strong')?.textContent?.trim()||'';const question=content.querySelector('.question-card h2')?.textContent?.trim()||'';const body=content.textContent||'';if(photo){set('Evia’s advice',photoAdvice(photo));return}if(question){set('Evia’s advice','Answer in your own words. Explain what you did, how you did it and why, using the question to guide you.');return}if(/This duty is complete/.test(body)){set('Evia’s advice','This duty is complete. Choose another duty when you are ready.');return}if(/All done\./.test(body)){set('Evia’s advice','That evidence is saved on your device. I’ll remember the KSBs you have already covered.');return}if(/What do you want to work on today\?/.test(body)){set('Evia’s advice','Choose a duty and I’ll guide you through the evidence one step at a time.');return}if(/What are you working on\?/.test(body)){set('Evia’s advice','Choose the activity you are doing. I’ll show you exactly what evidence to capture.');return}set('Evia’s advice','I’ll guide you through each step. Take your time and make sure the evidence clearly shows the work.')}
const observer=new MutationObserver(()=>requestAnimationFrame(update));observer.observe(content,{childList:true,subtree:true,characterData:true});anchor.addEventListener('click',()=>setTimeout(update,30));update();
})();