(function(){'use strict';
const app=document.getElementById('eviaApp'),anchor=document.getElementById('eviaAnchor'),content=document.getElementById('content'),copy=document.getElementById('homeCopy');
const course=window.EVIA_COURSE;
const KEY='evia3_evidence_v1';
const state={screen:'home',duty:null,activity:null,step:'intro',photoIndex:0,questionIndex:0,data:load()};
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{"met":{"S":[],"K":[],"B":[]},"activities":{}}')}catch{return {met:{S:[],K:[],B:[]},activities:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.data))}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function activity(id){return course.activities.find(a=>a.id===id)}
function duty(id){return course.duties.find(d=>d.id===id)}
function met(type,id){return state.data.met[type]?.includes(id)}
function mark(type,id){state.data.met[type]??=[];if(!state.data.met[type].includes(id))state.data.met[type].push(id);save()}
function record(a){state.data.activities[a.id]??={photos:{},answers:{}};return state.data.activities[a.id]}
function remaining(a){return {S:a.S.filter(x=>!met('S',x)),K:a.K.filter(x=>!met('K',x)),B:a.B.filter(x=>!met('B',x))}}
function escAll(arr){return arr.map(esc).join(' · ')}
function openHome(){state.screen='home';state.duty=null;state.activity=null;app.classList.remove('is-open');content.innerHTML='';copy.style.display='';render()}
anchor.addEventListener('click',()=>{if(state.screen==='home'){app.classList.add('is-open');copy.style.display='none';state.screen='duties';render()}else openHome()});
function render(){if(state.screen==='duties')renderDuties();else if(state.screen==='duty')renderDuty();else if(state.screen==='activity')renderActivity();}
function renderDuties(){content.innerHTML=`<div class="evia-sheet"><div class="evia-speech"><b>What do you want to work on today?</b><span>Choose a duty and I’ll guide you through it, one step at a time.</span></div><div class="course-label">${esc(course.title)} · ST0095 · v${esc(course.version)}</div><div class="duty-list">${course.duties.map((d,i)=>{const subs=d.activities.map(activity).filter(a=>{const r=remaining(a);return r.S.length||r.K.length||r.B.length});const done=d.activities.length>0&&!subs.length;return `<button class="duty-card ${done?'done':''}" onclick="chooseDuty('${d.id}')"><span class="duty-no">${String(i+1).padStart(2,'0')}</span><span><b>${esc(d.title)}</b><small>${esc(d.summary)}</small><em>${done?'Completed':d.activities.length?subs.length+' option'+(subs.length===1?'':'s'):'Development reflection'}</em></span><strong>${done?'✓':'›'}</strong></button>`}).join('')}</div></div>`}
window.chooseDuty=function(id){state.duty=duty(id);state.screen='duty';render()};
window.back=function(){if(state.screen==='activity'){state.screen='duty';render()}else if(state.screen==='duty'){state.screen='duties';render()}else openHome()};
function renderDuty(){const d=state.duty;const options=d.activities.map(activity).filter(a=>{const r=remaining(a);return r.S.length||r.K.length||r.B.length});content.innerHTML=`<div class="evia-sheet"><button class="back-btn" onclick="back()">‹ Duties</button><div class="evia-speech"><b>${esc(d.title)}</b><span>${esc(d.summary)} Pick what you are doing and I’ll guide you through the evidence.</span></div>${options.length?`<div class="sub-title">What are you working on?</div><div class="sub-list">${options.map(a=>{const r=remaining(a);return `<button class="sub-card" onclick="chooseActivity('${a.id}')"><span><b>${esc(a.title)}</b><small>${esc(a.summary)}</small><em>${r.S.length?'Skills '+r.S.join(', '):''}${r.K.length?' · Knowledge '+r.K.join(', '):''}${r.B.length?' · Behaviours '+r.B.join(', '):''}</em></span><strong>›</strong></button>`}).join('')}</div>`:`<div class="saved-card"><b>This duty is complete.</b><span>There is no remaining evidence to collect here.</span></div>`}</div>`}
window.chooseActivity=function(id){state.activity=activity(id);state.screen='activity';state.step='intro';state.photoIndex=0;state.questionIndex=0;render()};
function renderActivity(){const a=state.activity;if(state.step==='intro')return intro(a);if(state.step==='photos')return photoStep(a);if(state.step==='questions')return questionStep(a);return finished(a)}
function intro(a){const r=remaining(a),photos=a.photos.slice(0,5);content.innerHTML=`<div class="evia-sheet"><button class="back-btn" onclick="back()">‹ ${esc(state.duty.title)}</button><div class="evia-speech"><b>Let’s work on ${esc(a.title)}.</b><span>${esc(a.summary)}</span></div><section class="guide-card"><h2>Photos I’ll ask for</h2><p>I’ll ask for these one at a time. If you don’t have a photo, you can skip it.</p><ol>${photos.map(p=>`<li>${esc(p)}</li>`).join('')}</ol><div class="ksb-mini">${r.S.length?`<span>${r.S.length} Skills</span>`:''}${r.K.length?`<span>${r.K.length} Knowledge questions</span>`:''}${r.B.length?`<span>${r.B.length} Behaviour questions</span>`:''}</div><button class="primary" onclick="startPhotos()">I’m ready to take photos</button></section></div>`}
window.startPhotos=function(){state.step='photos';state.photoIndex=0;render()};
function photoStep(a){const photos=a.photos.slice(0,5),p=photos[state.photoIndex],d=record(a),n=state.photoIndex+1,has=!!d.photos[n];content.innerHTML=`<div class="evia-sheet"><button class="back-btn" onclick="back()">‹ ${esc(a.title)}</button><div class="evia-speech"><b>Photo ${n} of ${photos.length}</b><span>Show me: <strong>${esc(p)}</strong></span></div><section class="capture-card"><div class="capture-preview ${has?'has':''}">${has?`<img src="${d.photos[n]}" alt="Captured evidence photo ${n}">`:'<span>Camera photo will appear here</span>'}</div><label class="primary camera">${has?'Retake photo':'Take photo'}<input type="file" accept="image/*" capture="environment" onchange="capturePhoto(this)"></label><button class="skip" onclick="skipPhoto()">Skip this photo</button><div class="progress-dots">${photos.map((_,i)=>`<i class="${i===state.photoIndex?'current':i<state.photoIndex?'done':''}"></i>`).join('')}</div></section></div>`}
window.capturePhoto=function(input){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{record(state.activity).photos[state.photoIndex+1]=reader.result;save();nextPhoto()};reader.readAsDataURL(file)};
window.skipPhoto=function(){nextPhoto()};
function nextPhoto(){const a=state.activity;if(state.photoIndex<a.photos.slice(0,5).length-1){state.photoIndex++;render();return}state.step='questions';state.questionIndex=0;render()}
function questions(a){const r=remaining(a);return [...r.K.map(id=>({type:'K',id,q:course.KQ[id]})),...r.B.map(id=>({type:'B',id,q:course.BQ[id]}))]}
function questionStep(a){const qs=questions(a),q=qs[state.questionIndex],d=record(a);if(!q)return finishActivity();const old=d.answers[q.id]||'';content.innerHTML=`<div class="evia-sheet"><div class="evia-speech"><b>${q.type==='K'?'Knowledge':'Behaviour'} question</b><span>${q.type==='K'?'Answer in your own words.':'Tell me what you did and how you demonstrated it.'}</span></div><section class="question-card"><div class="q-badge">${esc(q.id)}</div><h2>${esc(q.q)}</h2><textarea id="answer" placeholder="Type your answer…">${esc(old)}</textarea><div class="question-actions"><button class="skip" onclick="skipQuestion()">Skip</button><button class="primary small" onclick="saveQuestion()">${state.questionIndex===qs.length-1?'Finish':'Next'}</button></div><div class="question-count">Question ${state.questionIndex+1} of ${qs.length}</div></section></div>`}
window.saveQuestion=function(){const a=state.activity,q=questions(a),el=document.getElementById('answer');if(!el)return;const v=el.value.trim();if(v){record(a).answers[q[state.questionIndex].id]=v;mark(q[state.questionIndex].type,q[state.questionIndex].id)}save();nextQuestion()};
window.skipQuestion=function(){nextQuestion()};
function nextQuestion(){const a=state.activity;if(state.questionIndex<questions(a).length-1){state.questionIndex++;render()}else finishActivity()}
function finishActivity(){const a=state.activity,d=record(a),captured=Object.keys(d.photos).length;if(captured){a.S.forEach(id=>mark('S',id))}save();state.step='finished';render()}
function finished(a){const d=record(a);content.innerHTML=`<div class="evia-sheet"><div class="evia-speech"><b>All done.</b><span>I’ve saved this work on your device. I’ll remember the KSBs you’ve already covered and won’t ask you for them again in later duties.</span></div><section class="saved-card"><div><b>${esc(a.title)} saved</b><span>${Object.keys(d.photos).length} photo${Object.keys(d.photos).length===1?'':'s'} captured · ${Object.keys(d.answers).length} question${Object.keys(d.answers).length===1?'':'s'} answered</span></div><button class="primary" onclick="backToDuties()">Back to duties</button></section></div>`}
window.backToDuties=function(){state.screen='duties';state.activity=null;render()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
})();