window.EVIA_COURSE={id:'ST0095',title:'Bricklayer',version:'1.2',source:'Naxos3.0',units:[
{id:'mixing-mortar',title:'Mixing Mortar',summary:'Prepare, mix and finish mortar safely to the required ratio and consistency.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE being worn for the task',ksb:['S2 · K2']},{show:'Safe controls before mixing starts',ksb:['S1 · K1']},{show:'Safe mixing area and controls',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why is it required for this task?'},{id:'K1',text:'What hazards have you identified before starting?'},{id:'K3',text:'What safe working controls are being followed before you begin?'}]},
{title:'Preparation',evidence:[{show:'Tools ready for mixing',ksb:['S8 · K13']},{show:'Sand, cement and other materials',ksb:['S6 · K8 · K12']},{show:'Required mix ratio/specification',ksb:['S5 · K10']}],questions:[{id:'K13',text:'Which tools are you using and what is each one used for?'},{id:'K8',text:'What are the materials you are using and what are their relevant characteristics?'},{id:'K12',text:'How did you determine the quantities required?'},{id:'K10',text:'What information did you take from the specification or instructions?'}]},
{title:'The Job',evidence:[{show:'Materials being measured/gauged',ksb:['S14 · K20']},{show:'Mortar being mixed',ksb:['S14 · K20']},{show:'Correct mortar consistency',ksb:['S14 · K20']}],questions:[{id:'K20',text:'How are you achieving the correct mortar ratio?'},{id:'K20',text:'What mixing method are you using and why?'},{id:'K20',text:'How do you know the mortar has reached the correct consistency?'}]},
{title:'Finish',evidence:[{show:'Tools cleaned and stored',ksb:['S9 · K13']},{show:'Remaining materials protected/stored',ksb:['S17 · K25']},{show:'Waste separated/disposed of correctly',ksb:['S3 · K4']}],questions:[{id:'K13',text:'How do you maintain and store the tools after use?'},{id:'K25',text:'How have you protected the remaining materials?'},{id:'K4',text:'How have you dealt with waste and reusable materials?'}]}]},
{id:'loading-out',title:'Loading Out',summary:'Select, move and position materials safely without damage.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Manual-handling controls',ksb:['S1 · K1']},{show:'Safe loading/unloading area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why is it required for this task?'},{id:'K1',text:'What hazards and manual-handling controls have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Tools/equipment required',ksb:['S8 · K13']},{show:'Materials being loaded out',ksb:['S6 · K8 · K12']},{show:'Drawings/job information being used',ksb:['S5 · K10']}],questions:[{id:'K13',text:'Which tools/equipment are you using and what is each one used for?'},{id:'K8',text:'What are the materials and their relevant characteristics?'},{id:'K12',text:'How did you determine the quantities required?'},{id:'K10',text:'What information did you take from the drawing, specification or instructions?'}]},
{title:'The Job',evidence:[{show:'Correct materials selected',ksb:['S6 · K8 · K12']},{show:'Materials positioned for the work',ksb:['S6 · K12']},{show:'Materials positioned without causing damage',ksb:['S6 · K8']}],questions:[{id:'K8',text:'Why are these materials suitable?'},{id:'K12',text:'How did you confirm the required quantities and location?'},{id:'K8',text:'How did the material characteristics affect how you handled or positioned them?'}]},
{title:'Finish',evidence:[{show:'Materials stored/protected',ksb:['S17 · K25']},{show:'Tools/equipment stored',ksb:['S9 · K13']},{show:'Waste/materials dealt with correctly',ksb:['S3 · K4']}],questions:[{id:'K25',text:'How have you protected the materials?'},{id:'K13',text:'How do you maintain and store the tools/equipment?'},{id:'K4',text:'How have you dealt with waste and reusable materials?'}]}]},
{id:'setting-out-cavity',title:'Setting Out Cavity',summary:'Set out cavity wall positions, dimensions, openings and returns accurately.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe setting-out area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified before starting?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Drawing/specification being used',ksb:['S5 · K10']},{show:'Materials/resources selected',ksb:['S6 · K12 · K8']},{show:'Setting-out tools',ksb:['S8 · K13']}],questions:[{id:'K10',text:'How did you interpret the drawing/specification?'},{id:'K12',text:'How did you determine the quantities/resources required?'},{id:'K8',text:'What are the relevant characteristics of the materials?'},{id:'K13',text:'Which setting-out tools are you using and why?'}]},
{title:'The Job',evidence:[{show:'Cavity wall position/profile',ksb:['S10 · K21']},{show:'Gauge, levels and dimensions',ksb:['S10 · K21']},{show:'Opening/return set out',ksb:['S10 · K21']}],questions:[{id:'K21',text:'How did you establish the cavity width and position?'},{id:'K21',text:'How are you maintaining the required levels and dimensions?'},{id:'K21',text:'How did you set out the opening correctly?'}]},
{title:'Finish',evidence:[{show:'Completed setting out',ksb:['S10 · K21']},{show:'Setting-out tools stored',ksb:['S9 · K13']},{show:'Area/materials protected',ksb:['S17 · K25']}],questions:[{id:'K21',text:'How did you check the completed setting out?'},{id:'K13',text:'How do you maintain and store the tools?'},{id:'K25',text:'How have you protected the area/materials?'}]}]},
{id:'building-cavity',title:'Building Cavity',summary:'Construct cavity walling and its key cavity, opening, fire and drainage details.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Drawings/specification',ksb:['S5 · K10']},{show:'Bricks, blocks and cavity materials',ksb:['S6 · K8 · K12']},{show:'Tools ready',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the drawing/specification?'},{id:'K8',text:'What are the materials and their characteristics?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Cavity wall construction',ksb:['S11 · K22']},{show:'Wall ties/insulation',ksb:['S11 · K22']},{show:'DPC/cavity tray',ksb:['S11 · K22']}],questions:[{id:'K22',text:'How are you constructing the cavity wall?'},{id:'K22',text:'How are wall ties and insulation being installed correctly?'},{id:'K22',text:'How are the DPC and cavity tray providing the required protection?'}]},
{title:'The Job · 2',evidence:[{show:'Fire stopping',ksb:['S11 · K22']},{show:'Lintel/opening/closure',ksb:['S11 · K22 · K23']},{show:'Weep holes/ventilation',ksb:['S11 · K22']}],questions:[{id:'K22',text:'How are you maintaining the required fire stopping?'},{id:'K22',text:'How does the opening detail form part of the cavity wall?'},{id:'K23',text:'How is the soldier/brick-on-edge detail set out and constructed where used?'},{id:'K22',text:'How are weep holes/ventilation provided correctly?'}]},
{title:'The Job · 3',evidence:[{show:'Joint finish',ksb:['S12 · K17']},{show:'Brick/block cutting where required',ksb:['S15 · K29']}],questions:[{id:'K17',text:'What joint finish are you using and how is it produced?'},{id:'K29',text:'How are the bricks/blocks measured, marked and cut?'}]},
{title:'Finish',evidence:[{show:'Finished/protected wall',ksb:['S17 · K25']},{show:'Tools cleaned/stored',ksb:['S9 · K13']},{show:'Waste/reusable material separated',ksb:['S3 · K4']}],questions:[{id:'K25',text:'How have you protected the completed work?'},{id:'K13',text:'How do you maintain and store the tools?'},{id:'K4',text:'How have you dealt with waste and reusable material?'}]}]},
{id:'cavity-openings',title:'Cavity Openings',summary:'Set out and construct cavity openings, lintels, closures, trays and associated details.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Opening-related hazards/controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards and controls apply to the opening?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Opening drawing/detail',ksb:['S5 · K10']},{show:'Materials for the opening',ksb:['S6 · K8 · K12']},{show:'Tools for the work',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the opening detail?'},{id:'K8',text:'What materials and characteristics are relevant?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Opening set out',ksb:['S10 · K21']},{show:'Lintel installed',ksb:['S11 · K22']},{show:'Soldier/edge sill detail',ksb:['S11 · K23']}],questions:[{id:'K21',text:'How did you establish the opening position and dimensions?'},{id:'K22',text:'How is the lintel installed and supported correctly?'},{id:'K23',text:'How is the soldier/brick-on-edge detail set out and constructed?'}]},
{title:'The Job · 2',evidence:[{show:'Closure around opening',ksb:['S11 · K22']},{show:'Insulation/fire stopping',ksb:['S11 · K22']},{show:'DPC/cavity tray',ksb:['S11 · K22']}],questions:[{id:'K22',text:'How is the cavity closure formed correctly?'},{id:'K22',text:'How are insulation and fire stopping maintained around the opening?'},{id:'K22',text:'How is the DPC/cavity tray detail constructed?'}]},
{title:'The Job · 3',evidence:[{show:'Weep holes',ksb:['S11 · K22']},{show:'Cutting around the opening',ksb:['S15 · K29']}],questions:[{id:'K22',text:'How are weep holes provided correctly?'},{id:'K29',text:'How are units measured, marked and cut to fit?'}]},
{title:'Finish',evidence:[{show:'Finished opening/detail',ksb:['S11 · K22']},{show:'Finished joints',ksb:['S12 · K17']},{show:'Work protected',ksb:['S17 · K25']}],questions:[{id:'K22',text:'How do you know the finished opening detail is correct?'},{id:'K17',text:'What joint finish is used and how is it produced?'},{id:'K25',text:'How have you protected the finished work?'}]}]},
{id:'setting-out-solid',title:'Setting Out Solid',summary:'Set out solid wall position, dimensions, bond, gauge, line and level.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Drawing/specification',ksb:['S5 · K10']},{show:'Bricks/materials selected',ksb:['S6 · K8 · K12']},{show:'Setting-out tools',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the drawing/specification?'},{id:'K8',text:'What are the material characteristics?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job',evidence:[{show:'Wall position/dimensions',ksb:['S13 · K16']},{show:'Bond selected/set out',ksb:['S13 · K15']},{show:'Gauge, line and level',ksb:['S13 · K16']}],questions:[{id:'K16',text:'How did you establish the wall position and dimensions?'},{id:'K15',text:'Which bond have you selected and how is it formed?'},{id:'K16',text:'How are you maintaining gauge, line and level?'}]},
{title:'Finish',evidence:[{show:'Completed setting out',ksb:['S13 · K16']},{show:'Tools stored',ksb:['S9 · K13']},{show:'Work/materials protected',ksb:['S17 · K25']}],questions:[{id:'K16',text:'How did you check the completed setting out?'},{id:'K13',text:'How do you maintain and store the tools?'},{id:'K25',text:'How have you protected the work/materials?'}]}]},
{id:'building-solid',title:'Building Solid',summary:'Construct solid walling using the correct bond, mortar, cutting and joint finish.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Drawing/specification',ksb:['S5 · K10']},{show:'Materials selected',ksb:['S6 · K8 · K12']},{show:'Tools ready',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the drawing/specification?'},{id:'K8',text:'What materials are being used and what are their characteristics?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Mortar prepared',ksb:['S14 · K20']},{show:'First course/bond',ksb:['S13 · K15 · K16']},{show:'Wall construction',ksb:['S13 · K16']}],questions:[{id:'K20',text:'How have you mixed the mortar to the required ratio and consistency?'},{id:'K15',text:'Which bond is being formed?'},{id:'K16',text:'How did you set out and construct the first course?'},{id:'K16',text:'How are you constructing the solid wall?'}]},
{title:'The Job · 2',evidence:[{show:'Bond and alignment',ksb:['S13 · K15 · K16']},{show:'Brick/block cutting where required',ksb:['S15 · K29']},{show:'Joint finish',ksb:['S12 · K17']}],questions:[{id:'K15',text:'How are you maintaining the bond?'},{id:'K16',text:'How are you maintaining alignment?'},{id:'K29',text:'How are units measured, marked and cut?'},{id:'K17',text:'What joint finish are you using and how is it produced?'}]},
{title:'Finish',evidence:[{show:'Completed wall',ksb:['S13 · K16']},{show:'Work protected',ksb:['S17 · K25']},{show:'Tools cleaned/stored',ksb:['S9 · K13']}],questions:[{id:'K16',text:'How did you check the completed wall?'},{id:'K25',text:'How have you protected the completed work?'},{id:'K13',text:'How do you maintain and store the tools?'}]}]},
{id:'solid-capping',title:'Solid Capping',summary:'Set out and construct solid capping accurately, including cutting and joint finish.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Capping detail/drawing',ksb:['S5 · K10']},{show:'Capping materials',ksb:['S6 · K8 · K12']},{show:'Tools selected',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the capping detail?'},{id:'K8',text:'What materials and characteristics are relevant?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Capping set out',ksb:['S13 · K16']},{show:'Capping being constructed',ksb:['S13 · K16']},{show:'Bond/detail of capping',ksb:['S13 · K15 · K16']}],questions:[{id:'K16',text:'How did you set out the capping?'},{id:'K16',text:'How are you constructing the capping?'},{id:'K15',text:'How is the bond/detail formed?'},{id:'K16',text:'How are dimensions maintained?'}]},
{title:'The Job · 2',evidence:[{show:'Cutting required pieces',ksb:['S15 · K29']},{show:'Joint finish',ksb:['S12 · K17']}],questions:[{id:'K29',text:'How are pieces measured, marked and cut?'},{id:'K17',text:'What joint finish are you using?'}]},
{title:'Finish',evidence:[{show:'Completed capping',ksb:['S13 · K16']},{show:'Finished work protected',ksb:['S17 · K25']},{show:'Tools stored',ksb:['S9 · K13']}],questions:[{id:'K16',text:'How did you check the completed capping?'},{id:'K25',text:'How have you protected the finished work?'},{id:'K13',text:'How do you maintain and store the tools?'}]}]},
{id:'repair-work',title:'Repair Work',summary:'Assess defects, remove damaged masonry, repair it and finish it to match.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Hazards/controls around repair',ksb:['S1 · K1']},{show:'Safe repair area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards and controls have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Defect/damaged area',ksb:['S16 · K24']},{show:'Work instruction/drawing',ksb:['S5 · K10']},{show:'Tools/materials selected',ksb:['S8 · K13']}],questions:[{id:'K24',text:'What defect have you identified and what repair is required?'},{id:'K10',text:'What information did you take from the work instruction/drawing?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Defect being assessed',ksb:['S16 · K24']},{show:'Damaged material being removed',ksb:['S16 · K24']},{show:'Replacement material being installed',ksb:['S16 · K24 · K8']}],questions:[{id:'K24',text:'How did you assess the defect?'},{id:'K24',text:'How are you removing the damaged material and preparing the area?'},{id:'K24',text:'How are you carrying out the repair?'},{id:'K8',text:'Why is the replacement material suitable?'}]},
{title:'The Job · 2',evidence:[{show:'Brick/block cut to fit',ksb:['S15 · K29']},{show:'Repair joint finish',ksb:['S12 · K17']}],questions:[{id:'K29',text:'How is the replacement unit measured, marked and cut?'},{id:'K17',text:'How are the repair joints finished to match the work?'}]},
{title:'Finish',evidence:[{show:'Completed repair',ksb:['S16 · K24']},{show:'Finished work protected',ksb:['S17 · K25']},{show:'Waste dealt with correctly',ksb:['S3 · K4']}],questions:[{id:'K24',text:'How do you know the repair is complete and suitable?'},{id:'K25',text:'How have you protected the finished work?'},{id:'K4',text:'How have you dealt with waste and reusable materials?'}]}]},
{id:'raked-walling',title:'Raked Walling',summary:'Set out, construct and finish raking walling accurately.',stages:[
{title:'Health & Safety',evidence:[{show:'PPE/RPE',ksb:['S2 · K2']},{show:'Safe working controls',ksb:['S1 · K1']},{show:'Safe working area',ksb:['S7 · K3']}],questions:[{id:'K2',text:'What PPE/RPE are you using and why?'},{id:'K1',text:'What hazards have you identified?'},{id:'K3',text:'What safe working controls are being followed?'}]},
{title:'Preparation',evidence:[{show:'Raking/gable drawing',ksb:['S5 · K10']},{show:'Materials selected',ksb:['S6 · K8 · K12']},{show:'Tools selected',ksb:['S8 · K13']}],questions:[{id:'K10',text:'What information did you take from the drawing?'},{id:'K8',text:'What materials and characteristics are relevant?'},{id:'K12',text:'How did you determine quantities?'},{id:'K13',text:'Which tools are you using and why?'}]},
{title:'The Job · 1',evidence:[{show:'Rake set out',ksb:['S22 · K30']},{show:'Raking wall being constructed',ksb:['S22 · K30']},{show:'Rake/profile maintained',ksb:['S22 · K30']}],questions:[{id:'K30',text:'How is the rake set out?'},{id:'K30',text:'How is the raking wall constructed?'},{id:'K30',text:'How are the required rake and profile maintained?'}]},
{title:'The Job · 2',evidence:[{show:'Bricks/blocks cut to the required shape',ksb:['S15 · K29']},{show:'Completed raking detail',ksb:['S22 · K30']}],questions:[{id:'K29',text:'How are the bricks/blocks measured, marked and cut to the required shape?'},{id:'K30',text:'How do you know the completed raking detail is correct?'}]},
{title:'Finish',evidence:[{show:'Finished joints',ksb:['S12 · K17']},{show:'Completed raking wall protected',ksb:['S17 · K25']},{show:'Tools/materials/waste dealt with',ksb:['S3 · K4']}],questions:[{id:'K17',text:'What joint finish are you using and how is it produced?'},{id:'K25',text:'How have you protected the completed raking wall?'},{id:'K4',text:'How have you dealt with tools, materials, waste and reusable materials?'}]}]}
]};